name: mt_metadata-docs
channels:
  # Don't change to pkgs/main, as it causes random timeouts in readthedocs
  - conda-forge
dependencies:
  - python=3.7
  - ipykernel
  - ipython
  - jupyter_client
  - nbsphinx
  - numpy>=1.17
  - pandas
  - obspy
  - matplotlib
  - setuptools
  - sphinx>=2.3
  - sphinx_rtd_theme>=0.4
  - PyYAML
  - pip
  - pip:
    - concurrent_log_handler
