name: TestingInConda

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: mtmetadata-test
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      run: |
        python --version
        conda install -c conda-forge pytest pytest-cov
        
    - name: Install Our Package
      shell: bash
      run: |
        pip install -e .
        conda list
        pip freeze
        
    - name: Run Tests
      run: pytest --cov=./ --cov-report=xml --cov=mt_metadata
        
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
        verbose: true
        flags: tests
        
