name: TestingInConda

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Conda
      uses: s-weigand/setup-conda@v1.0.7
      with:
        update-conda: false
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      shell: bash
      run: |
        python --version
        conda create -n mtmetadata-test python=${{ matrix.python-version }}
        source activate mtmetadata-test
        conda install pytest
        conda install pytest-cov
        
    - name: Install Our Package
      shell: bash
      run: |
        source activate mtmetadata-test
        pip install -e .
        conda list
    - name: Run Tests
      shell: bash
      run: |
        source activate mtmetadata-test
        pytest --cov=./ --cov-report=xml --cov=mt_metadata
        
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
        verbose: true
        flags: tests
        
